### ISSUE TITLE
webpack-parallel-simple: Is @swc-node/register needed?

### ISSUE THREAD

**Issue by vpzomtrrfrt** [dkazakov8/dk-framework#1]
I assume that's in there to load typescript config files, but couldn't the caller import swc-node themselves? I don't want to pull swc into my project just for this

**Comment by dkazakov8** [comment]
OK, I removed SWC dependency for this library since version 3.2.6. Now ts-parsing is handled by [tsx](https://www.npmjs.com/package/tsx) and this library is included in deps of webpack-parallel-simple.
